<a href="https://colab.research.google.com/github/MasudurRahman34/Business_Analysis/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#import numpy from libraries
import numpy as np
np.__version__

'1.26.4'

In [3]:
#creating array from numpy
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
#numpy array can be multidimetional
#1d, 2d, 3d....nd array.
type(arr)

numpy.ndarray

In [5]:
def getInfoOfArrayObject(obj):
  print(f'array elements= {(obj)}')
  print(f'type of the object= {type(obj)}')

  print(f'dimenttion of the object= {obj.ndim}')
  print(f'shape of the object ={obj.shape}')
  print(f'size of the array: ={obj.size}')
  print(f'data type of the object ={obj.dtype}')


In [6]:
getInfoOfArrayObject(arr)

array elements= [ 1  2  3  4  5  6  7  8  9 10]
type of the object= <class 'numpy.ndarray'>
dimenttion of the object= 1
shape of the object =(10,)
size of the array: =10
data type of the object =int64



```
shape
1d object = row for example (4,)
2d object = row,column for example(3,3)
3d object = layer, (row, column) for example (2,(2,3))
```

In [7]:
#2d array
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
getInfoOfArrayObject(arr2)


array elements= [[1 2 3]
 [4 5 6]
 [7 8 9]]
type of the object= <class 'numpy.ndarray'>
dimenttion of the object= 2
shape of the object =(3, 3)
size of the array: =9
data type of the object =int64


In [8]:
#3d array
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
getInfoOfArrayObject(arr3)

array elements= [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
type of the object= <class 'numpy.ndarray'>
dimenttion of the object= 3
shape of the object =(2, 2, 3)
size of the array: =12
data type of the object =int64


In [9]:
#array one
arr4=np.ones((3,4), dtype=int)
getInfoOfArrayObject(arr4)

array elements= [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
type of the object= <class 'numpy.ndarray'>
dimenttion of the object= 2
shape of the object =(3, 4)
size of the array: =12
data type of the object =int64


In [10]:
#arrithmetic with array
arrAdd=arr4+99
getInfoOfArrayObject(arrAdd)

array elements= [[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
type of the object= <class 'numpy.ndarray'>
dimenttion of the object= 2
shape of the object =(3, 4)
size of the array: =12
data type of the object =int64


In [11]:
#array arrange for sequencing
arrSeq=np.arange(1,10, step=1)
arraRevSeq=np.arange(10,0,-1)
getInfoOfArrayObject(arrSeq)
getInfoOfArrayObject(arraRevSeq)

array elements= [1 2 3 4 5 6 7 8 9]
type of the object= <class 'numpy.ndarray'>
dimenttion of the object= 1
shape of the object =(9,)
size of the array: =9
data type of the object =int64
array elements= [10  9  8  7  6  5  4  3  2  1]
type of the object= <class 'numpy.ndarray'>
dimenttion of the object= 1
shape of the object =(10,)
size of the array: =10
data type of the object =int64


In [12]:
#array linspace for eqally spaced over the specified range, parameter num, endpoint dtype
arrLinspace=np.linspace(0,1, num=5)
getInfoOfArrayObject(arrLinspace)
#endpoint false means it exclude last range here is 1
arrLinspace=np.linspace(0,1, num=5, endpoint=False)
getInfoOfArrayObject(arrLinspace)

array elements= [0.   0.25 0.5  0.75 1.  ]
type of the object= <class 'numpy.ndarray'>
dimenttion of the object= 1
shape of the object =(5,)
size of the array: =5
data type of the object =float64
array elements= [0.  0.2 0.4 0.6 0.8]
type of the object= <class 'numpy.ndarray'>
dimenttion of the object= 1
shape of the object =(5,)
size of the array: =5
data type of the object =float64




```
DIFFERENCE
Feature	np.arange	np.linspace
Spacing	Defined by step	Determined to fit num elements
Endpoint	Excluded (stop)	Included by default (endpoint=True)
Usage	When you know the step size	When you know the number of elements
```



In [13]:
#reshape can convert the array with n dimentional
arr8=np.arange(1,13).reshape(3,-1)
getInfoOfArrayObject(arr8)

array elements= [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
type of the object= <class 'numpy.ndarray'>
dimenttion of the object= 2
shape of the object =(3, 4)
size of the array: =12
data type of the object =int64


In [14]:
#flatten array can convert any dimention into 1 dimention
arr9=arr8.flatten()
getInfoOfArrayObject(arr9)

array elements= [ 1  2  3  4  5  6  7  8  9 10 11 12]
type of the object= <class 'numpy.ndarray'>
dimenttion of the object= 1
shape of the object =(12,)
size of the array: =12
data type of the object =int64


In [15]:
arr10=np.arange(1,51).reshape(10,5)
getInfoOfArrayObject(arr10)

array elements= [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
type of the object= <class 'numpy.ndarray'>
dimenttion of the object= 2
shape of the object =(10, 5)
size of the array: =50
data type of the object =int64


In [16]:
arr11=np.linspace(1,50,50, dtype=int).reshape(10,5)
getInfoOfArrayObject(arr11)

array elements= [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
type of the object= <class 'numpy.ndarray'>
dimenttion of the object= 2
shape of the object =(10, 5)
size of the array: =50
data type of the object =int64


In [17]:
identity_matrix=np.eye(3, dtype=int)
getInfoOfArrayObject(identity_matrix)

array elements= [[1 0 0]
 [0 1 0]
 [0 0 1]]
type of the object= <class 'numpy.ndarray'>
dimenttion of the object= 2
shape of the object =(3, 3)
size of the array: =9
data type of the object =int64




```
mathemetic operation and universal function /scaler addition
```



In [19]:
arr12=np.arange(10)
arr13=np.arange(1,11)

print(arr12)
print(arr13)
print(arr12+arr13)
print(arr12-arr13)
print(arr12*arr13)
print(arr12/arr13)
print(arr12%arr13)

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0  2  6 12 20 30 42 56 72 90]
[0.         0.5        0.66666667 0.75       0.8        0.83333333
 0.85714286 0.875      0.88888889 0.9       ]
[0 1 2 3 4 5 6 7 8 9]
